services:
  odpc:
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_DB=ODPC
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localdev
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - OIDC_AUTHORITY=http://host.docker.internal:9090
      - OIDC_CLIENT_ID=localdev
      - OIDC_CLIENT_SECRET=localdev
      - OIDC_DISABLE_HTTPS=true
      - OIDC_NAME_CLAIM_TYPE=sub
      - OIDC_ROLE_CLAIM_TYPE=sub
      - OIDC_ID_CLAIM_TYPE=sub
    image: ${DOCKER_REGISTRY-}odpc
    build:
      context: .
      dockerfile: ODPC.Server/Dockerfile
    ports:
      - "62230:8080"
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=localdev
    restart: always
    ports:
      - "5432:5432"
  auth-mock:
    build:
      context: ./auth-mock
    environment:
      - PORT=9090
      - HOST=localhost
      - CLIENT_ID=localdev
      - CLIENT_SECRET=localdev
      - CLIENT_REDIRECT_URI_0=http://localhost:62230/signin-oidc
      - CLIENT_REDIRECT_URI_1=http://localhost:5173/signin-oidc
      - CLIENT_LOGOUT_REDIRECT_URI_0=http://localhost:62230/signout-callback-oidc
      - CLIENT_LOGOUT_REDIRECT_URI_1=http://localhost:5173/signout-callback-oidc
    ports:
      - 9090:9090
volumes:
  db:
